#!/bin/bash

echo "adding ip addresses"
ssh H1 ip address add 192.168.0.1/24 dev eth0
ssh H1 ip link set eth0 addr 00:00:00:00:00:1
ssh H1 ip link set dev eth0 up

ssh H2 ip address add 192.168.0.2/24 dev eth0
ssh H2 ip link set eth0 addr 00:00:00:00:00:2
ssh H2 ip link set dev eth0 up

ssh H3 ip address add 192.168.1.3/24 dev eth0
ssh H3 ip link set eth0 addr 00:00:00:00:00:3
ssh H3 ip link set dev eth0 up

ssh H4 ip address add 192.168.1.4/24 dev eth0
ssh H4 ip link set eth0 addr 00:00:00:00:00:4
ssh H4 ip link set dev eth0 up

echo "S1"
ssh S1 ip link set dev br0 down
ssh S1 ip link delete br0 type bridge

ssh S1 ip link add br0 type bridge
ssh S1 ip link set dev eth2 master br0
ssh S1 ip link set dev eth3 master br0

ssh S1 ip link add br1 type bridge
ssh S1 ip link set dev eth0 master br1
ssh S1 ip link set dev eth1 master br1

ssh S1 ip link set dev br0 up
ssh S1 ip link set dev br1 up

echo "S2"
ssh S2 ip link set dev br0 down
ssh S2 ip link delete br0 type bridge

ssh S2 ip link add br0 type bridge
ssh S2 ip link set dev eth2 master br0
ssh S2 ip link set dev eth3 master br0

ssh S2 ip link add br1 type bridge
ssh S2 ip link set dev eth0 master br1
ssh S2 ip link set dev eth1 master br1

ssh S2 ip link set dev br0 up
ssh S2 ip link set dev br1 up

echo "adding ip addresses to bridges"
ssh S1 ip address add 192.168.0.10/24 dev br0
ssh S1 ip link set br0 addr 00:00:00:00:00:10
ssh S1 ip link set dev br0 up

ssh S1 ip address add 192.168.1.10/24 dev br1
ssh S1 ip link set br1 addr 00:00:00:00:00:11
ssh S1 ip link set dev br1 up

ssh S2 ip address add 192.168.0.20/24 dev br0
ssh S2 ip link set br0 addr 00:00:00:00:00:20
ssh S2 ip link set dev br0 up

ssh S2 ip address add 192.168.1.20/24 dev br1
ssh S2 ip link set br1 addr 00:00:00:00:00:21
ssh S2 ip link set dev br1 up

echo "enabling ipv4 forwarding"
ssh S1 sysctl net.ipv4.ip_forward=1
ssh S2 sysctl net.ipv4.ip_forward=1

echo "adding routes"
ssh H1 ip route add default via 192.168.0.10 dev eth0
ssh H2 ip route add default via 192.168.0.20 dev eth0
ssh H3 ip route add default via 192.168.1.10 dev eth0
ssh H4 ip route add default via 192.168.1.20 dev eth0
