interfaces:
  - iface_name: eth0
    ip_address: 2.0.0.2
    netmask: 255.255.255.0
  - iface_name: eth1
    ip_address: 3.0.0.2
    netmask: 255.255.255.0
    post_up: ip route add 1.0.0.0/24 via 2.0.0.1