#!/bin/bash

#S1
ssh S1 ip link set dev br0 down
ssh S1 ip link delete br0 type bridge

ssh S1 ip link add br0 type bridge
ssh S1 ip link set dev eth0 master br0
ssh S1 ip link set dev eth1 master br0

ssh S1 ip link add br1 type bridge
ssh S1 ip link set dev eth2 master br1
ssh S1 ip link set dev eth3 master br1

ssh S1 ip link set dev br0 up
ssh S1 ip link set dev br1 up

# S2
ssh S2 ip link set dev br0 down
ssh S2 ip link delete br0 type bridge

ssh S2 ip link add br0 type bridge
ssh S2 ip link set dev eth0 master br0
ssh S2 ip link set dev eth1 master br0

ssh S2 ip link add br1 type bridge
ssh S2 ip link set dev eth2 master br1
ssh S2 ip link set dev eth3 master br1

ssh S2 ip link set dev br0 up
ssh S2 ip link set dev br1 up
