#!/usr/bin/expect -f
set timeout 5
set host [lindex $argv 0]
set port [lindex $argv 1]

spawn telnet $host $port
expect -re "> ?$"
send "dhclient -r\r"
send "dhclient -v mgmt0\r"
expect -re "> ?$"
send "exit\r"
expect eof