# Use root/example as user/password credentials
version: '3.9'

services:
  go:
    build:
      dockerfile: ./docker/go.Dockerfile
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_DB: myapp
      MYSQL_PASSWORD: example
    expose:
      - "3000"
    depends_on:
      - db
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/certs
    depends_on:
      - go
    ports:
      - 80:80
      - 443:443

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: myapp
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  mysql:
