# Use root/example as user/password credentials
version: '3.9'

services:
  go:
    build:
      dockerfile: ./docker/go.Dockerfile
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_DB: myapp
      MYSQL_PASSWORD: example
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: myapp
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080